#!/bin/bash
# This install script helps you, to compile the DataTool
# package.
# Current Version: 0.0.1 - paule32
#
tmp_file=$(tempfile 2>/dev/null) || tmp_file=/tmp/test$$
trap "rm -f $tmp_file" 0 1 2 5 15

dialog \
  --backtitle "DataTools 0.0.1 (c) Jens Kallup - paule32" \
  --title " Install path from Qt-5 " \
  --clear  \
  --inputbox \
"Hi, this is an input dialog box. You can use \n
it to ask for the installation path of QT5 \n
from the developer/user. \n
Please make sure, you have download Qt5 source\n
plus the Qt Creator 4.12.0. \n \n \n" 16 51 $QTDIR 2> $tmp_file

tmp_str=$(cat $tmp_file)

echo "export QTDIR=$tmp_str" > rc.local
echo "export PATH=$tmp_str/5.14.2/gcc_64/bin:$PATH" >> rc.local
echo "export LD_LIBRARY_PATH=$tmp_str/5.14.2/gcc_64/lib:$LD_LIBRARY_PATH" >> rc.local

dialog \
  --backtitle "DataTools 0.0.1 (c) Jens Kallup - paule32" \
  --title " ATTENTION " \
  --yesno "rc.local file was created. Would you use the collected \n
settings, and try to compile the DataTool package ?" 10 45
answer=$?
clear
if [ $answer = 0 ]; then
source rc.local
qmake
make
make install
else
echo "nothing to do, back on shell."
fi
echo "Have a nice day."
