#ifndef TOOLCOLLECTION_GLOBAL_H
#define TOOLCOLLECTION_GLOBAL_H

#if defined(TOOLCOLLECTION_LIBRARY)
#  define TOOLCOLLECTION_EXPORT Q_DECL_EXPORT
#else
#  define TOOLCOLLECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLCOLLECTION_GLOBAL_H
